<div class="multishipping">
    <h3><?php echo $this->__("Default") ?></h3>
    <table>
        <thead>
            <tr>
                <th><?php echo $this->__("enabled") ?></th><th><?php echo $this->__("limit") ?></th><th><?php echo $this->__("price") ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><select><option value="enabled"><?php echo $this->__("Enabled") ?></option><option value="disabled"><?php echo $this->__("Disabled") ?></option></select></td><td><input type="text"></td><td><input type="text"></td>
            </tr>
        </tbody>
    </table>

    <h3><?php echo $this->__("Detailed") ?></h3>

    <p><?php echo $this->__("Leave a field empty for it to inherit the default value.") ?></p>
    
    <table>
        <thead>
            <tr>
                <th rowspan="2"></th>
                <th colspan="3"><?php echo $this->__("Monday") ?></th>
                <th colspan="3"><?php echo $this->__("Tuesday") ?></th>
                <th colspan="3"><?php echo $this->__("Wednesday") ?></th>
                <th colspan="3"><?php echo $this->__("Thursday") ?></th>
                <th colspan="3"><?php echo $this->__("Friday") ?></th>
                <th colspan="3"><?php echo $this->__("Saturday") ?></th>
                <th colspan="3"><?php echo $this->__("Sunday") ?></th>
            </tr>
            <tr>
                <?php echo str_repeat("<th>". $this->__("enabled") ."</th><th>". $this->__("limit") ."</th><th>". $this->__("price") ."</th>", 7) ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?php echo $this->__("Default") ?></td>
                <?php for($j = 0; $j < 7; $j++): ?>
                    <td><select><option value="enabled"><?php echo $this->__("Enabled") ?></option><option value="disabled"><?php echo $this->__("Disabled") ?></option><option default value=""><?php echo $this->__("Default") ?></option></select><td><input type="text"></td><td><input type="text"></td>
                <?php endfor; ?>
            </tr>
            <?php for($i = 0; $i < 24; $i++): ?>
                <tr>
                    <td><?php echo $i ?></td>
                    <?php for($j = 0; $j < 7; $j++): ?>
                        <td><select><option value="enabled"><?php echo $this->__("Enabled") ?></option><option value="disabled"><?php echo $this->__("Disabled") ?></option><option default value=""><?php echo $this->__("Default") ?></option></select></td><td><input type="text"></td><td><input type="text" value="<?php if ($price = $this->getPrice($i, $j)) var_dump($price->getData()); ?>"></td>
                    <?php endfor; ?>                
            <?php endfor; ?>
        </tbody>
    </table>

</div>