<h1><?php echo Mage::helper('helloworld')->__('Stores'); ?></h1>
<?php foreach ($this->getWebsites() as $website): ?>
    <ul><h3><?php echo $website->getName() ?></h3>
    <?php foreach ($website->getGroups() as $group): ?>
        <?php $stores = $group->getStores(); ?>
        <?php foreach ($stores as $store): ?>     
           <li><?php echo (($store->getIsActive()) ? $store->getId().'. '.$store->getName() : '<span style="text-decoration: line-through">'.$store->getId().'. '.$store->getName()).'</span>' ?></li>
        <?php endforeach; ?>
    <?php endforeach; ?></ul>
<?php endforeach; ?>