<div class="field">
    <label for="billing:tax_number" class="required">
        <?php /*echo $this->__('Delivery Instructions')*/ echo "Tax/VAT Number"; ?>
    </label>
    <div class="input-box">
        <input type="text" name="billing[tax_number]" id="billing:tax_number" value="<?php /*echo $this->escapeHtml($this->getAddress()->getDeliveryInstruction())*/ echo '12'; ?>" title="<?php /*echo $this->__('Delivery Instructions')*/ echo "Tax/VAT Number"; ?>" class="input-text required-entry" />
    </div>
</div>