<?php $collection = $this->getProducts(); ?>
<?php $loggedSku = Mage::getStoreConfig('productlogger/messages/sku'); ?>
<h1><?php echo $this->__('Logs of specific products') ?></h1>
<?php if($collection->getSize()): ?>
<table class="data-table productlogger">
    <thead><tr><th><?php echo $this->__('Date bought') ?></th><th><?php echo $this->__('SKU') ?></th><th><?php echo $this->__('Product ID') ?></th><th><?php echo $this->__('Product name') ?></th><th><?php echo $this->__('Price') ?></th><th><?php echo $this->__('Quantity') ?></th></tr></thead>
    <?php foreach ($collection as $row): ?>
        <tr><td><?php echo $row->getOrderDate(); ?></td><td><?php echo $row->getSku(); ?></td><td><?php echo $row->getProductId(); ?></td><td><?php echo $row->getProductName(); ?></td><td><?php echo $row->getPrice(); ?></td><td><?php echo $row->getQty(); ?></td></tr>
    <?php endforeach; ?>
</table>
<?php echo $this->getPagerHtml() ?>
<?php else: ?>
    <p class="productlogger"><?php echo ( ( !($this->getRequest()->getParam('date_from')) || !($this->getRequest()->getParam('date_to')) ) ? $this->__('No products logged within the chosen interval.') : $this->__('No products logged so far.') ) ?></p>
<?php endif ?>
<form class="productlogger">
    <input type="text" name="date_from" id="date_from" class="input-text productlogger" placeholder="<?php echo $this->__("date from") ?>" value="<?php echo $this->getDateFrom() ?>"> 
    <input type="text" name="date_to" id="date_to" class="input-text productlogger" placeholder="<?php echo $this->__("date to") ?>" value="<?php echo $this->getDateTo() ?>">
    <?php echo $this->getButtonHtml() ?>
</form>
<p class="productlogger"><?php echo $this->__('At the moment logging products with SKU: <span>%s</span>.', $loggedSku) ?></p>
<script type="text/javascript">// <![CDATA[
Calendar.setup({
    inputField : 'date_from',
    ifFormat : '%Y-%m-%e',
    button : 'date_from_trig',
    align : 'Bl',
    singleClick : true
});

Calendar.setup({
    inputField : 'date_to',
    ifFormat : '%Y-%m-%e',
    button : 'date_to_trig',
    align : 'Bl',
    singleClick : true
});
// ]]></script>