<?php $collection = $this->getProducts(); ?>
<h1><?php echo $this->__('Logs of specific products') ?></h1>
<table>
    <thead><tr><th><?php echo $this->__('Date bought') ?></th><th><?php echo $this->__('SKU') ?></th><th><?php echo $this->__('Product ID') ?></th><th><?php echo $this->__('Product name') ?></th><th><?php echo $this->__('Price') ?></th><th><?php echo $this->__('Quantity') ?></th></tr></thead>
    <?php foreach ($collection as $row): ?>
        <tr><td><?php echo $row->getOrderDate(); ?></td><td><?php echo $row->getSku(); ?></td><td><?php echo $row->getProductId(); ?></td><td><?php echo $row->getProductName(); ?></td><td><?php echo $row->getPrice(); ?></td><td><?php echo $row->getQty(); ?></td></tr>
    <?php endforeach; ?>
</table>
<p><?php echo $this->__('At the moment logging products with SKU') ?>: <?php echo Mage::getStoreConfig('productlogger/messages/sku') ?>.</p>