<form id="co-multishipping-form">
<fieldset>
    <ul class="form-list">
    <li id="multishipping-form">
        <fieldset>
            <ul>
                <li class="wide">
                    <label for="multishipping:date" class="required"><em>*</em><?php echo $this->__('Delivery date:') ?></label>
                    <div class="ianput-box">
                        <input type="hidden" name="multishipping[date]" id="multishipping:date">
                        <table>
                            <thead>
                                <tr>
                                    <th></th>
                                    <th><?php echo $this->__("Monday") // TODO: replace with getDays() ?></th>
                                    <th><?php echo $this->__("Tuesday") ?></th>
                                    <th><?php echo $this->__("Wednesday") ?></th>
                                    <th><?php echo $this->__("Thursday") ?></th>
                                    <th><?php echo $this->__("Friday") ?></th>
                                    <th><?php echo $this->__("Saturday") ?></th>
                                    <th><?php echo $this->__("Sunday") ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                    <?php for($hour = 0; $hour < 24; $hour++): ?>
                                    <tr>
                                        <td><?php echo $hour ?>:00</td>
                                        <?php for($day = 0; $day < 7; $day++): // TODO: replace with getDays() ?>
                                            <td><?php echo $this->getRadio($day, $hour) ?></td>
                                        <?php endfor; ?>
                                    </tr>
                                    <?php endfor; ?>
                            </tbody>
                        </table>
                    </div>
                </li>
            </ul>
        </fieldset>
     </li>
    </ul>
    <div class="buttons-set" id="multishipping-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="multishipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span class="please-wait" id="multishipping-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var multishipping = new MultishippingMethod('co-multishipping-form','<?php echo $this->getUrl('checkout/onepage/saveMultishipping') ?>');
    var multishippingForm = new VarienForm('co-multishipping-form');
//]]>
</script>